framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        # buses:
        #     messenger.bus.default:
        #         # disable the default middleware
        #         default_middleware: false

        #         # and/or add your own
        #         middleware:
        #             # service ids that implement Symfony\Component\Messenger\Middleware\MiddlewareInterface
        #             - 'App\Middleware\CustomMiddleware'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\MailNotification: async
            # App\Message\ImageMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
